---
- name: configure ssh proxy via bastion host
  blockinfile:
    dest: '{{ ssh_config_file }}'
    create: true
    mode: 0600
    marker: '# {mark} OPENSHIFT ON GCP BLOCK'
    state: present
    block: |
      {% for item in groups['tag_' + prefix] %}
      Host {{ item }}
        User cloud-user
        IdentityFile ~/.ssh/google_compute_engine
        CheckHostIP no
        StrictHostKeyChecking no
      {% endfor %}
